version: '3.3'
services:
  mysql_db_container:
    image: arm64v8/mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: 'houmadev_db'
      # So you don't have to use houmadev_user, but you can if you like
      MYSQL_USER: 'houmadev_user'
      # You can use whatever houmadev_password you like
      MYSQL_PASSWORD: 'houmadev_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080

# Names our volume
volumes:
  my-db:
  
